default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, jquery.mobile-1.0a4.1.min.css]

  javascripts:    [jquery-1.5.2.min.js, jquery.mobile-1.0a4.1.min.js]

  has_layout:     true
  layout:         layout
